// All rooms by admin
export const ADMIN_ALL_ROOMS_REQUEST = "ADMIN_ALL_ROOMS_REQUEST";
export const ADMIN_ALL_ROOMS_SUCCESS = "ADMIN_ALL_ROOMS_SUCCESS";
export const ADMIN_ALL_ROOMS_FAILURE = "ADMIN_ALL_ROOMS_FAILURE";

// new room by admin
export const ADMIN_NEW_ROOM_REQUEST = "ADMIN_NEW_ROOM_REQUEST";
export const ADMIN_NEW_ROOM_SUCCESS = "ADMIN_NEW_ROOM_SUCCESS";
export const ADMIN_NEW_ROOM_FAILURE = "ADMIN_NEW_ROOM_FAILURE";
export const ADMIN_NEW_ROOM_RESET = "ADMIN_NEW_ROOM_RESET";

// update room by admin
export const ADMIN_UPDATE_ROOM_REQUEST = "ADMIN_UPDATE_ROOM_REQUEST";
export const ADMIN_UPDATE_ROOM_SUCCESS = "ADMIN_UPDATE_ROOM_SUCCESS";
export const ADMIN_UPDATE_ROOM_FAILURE = "ADMIN_UPDATE_ROOM_FAILURE";
export const ADMIN_UPDATE_ROOM_RESET = "ADMIN_UPDATE_ROOM_RESET";

// delete room by admin
export const ADMIN_DELETE_ROOM_SUCCESS = "ADMIN_DELETE_ROOM_SUCCESS";
export const ADMIN_DELETE_ROOM_REQUEST = "ADMIN_DELETE_ROOM_REQUEST";
export const ADMIN_DELETE_ROOM_FAILURE = "ADMIN_DELETE_ROOM_FAILURE";
export const ADMIN_DELETE_ROOM_RESET = "ADMIN_DELETE_ROOM_RESET";

// All bookings by admin
export const ADMIN_ALL_BOOKINGS_REQUEST = "ADMIN_ALL_BOOKINGS_REQUEST";
export const ADMIN_ALL_BOOKINGS_SUCCESS = "ADMIN_ALL_BOOKINGS_SUCCESS";
export const ADMIN_ALL_BOOKINGS_FAILURE = "ADMIN_ALL_BOOKINGS_FAILURE";

// delete booking by admin
export const ADMIN_DELETE_BOOKING_SUCCESS = "ADMIN_DELETE_BOOKING_SUCCESS";
export const ADMIN_DELETE_BOOKING_REQUEST = "ADMIN_DELETE_BOOKING_REQUEST";
export const ADMIN_DELETE_BOOKING_FAILURE = "ADMIN_DELETE_BOOKING_FAILURE";
export const ADMIN_DELETE_BOOKING_RESET = "ADMIN_DELETE_BOOKING_RESET";

// All users by admin
export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST";
export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS";
export const ADMIN_ALL_USERS_FAILURE = "ADMIN_ALL_USERS_FAILURE";

// get user details by admin
export const ADMIN_USER_DETAILS_REQUEST = "ADMIN_USER_DETAILS_REQUEST";
export const ADMIN_USER_DETAILS_SUCCESS = "ADMIN_USER_DETAILS_SUCCESS";
export const ADMIN_USER_DETAILS_FAILURE = "ADMIN_USER_DETAILS_FAILURE";

// update user by admin
export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_FAILURE = "ADMIN_UPDATE_USER_FAILURE";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";

// delete user by admin
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_FAILURE = "ADMIN_DELETE_USER_FAILURE";
export const ADMIN_DELETE_USER_RESET = "ADMIN_DELETE_USER_RESET";

// room reviews by admin
export const ADMIN_ALL_REVIEWS_REQUEST = "ADMIN_ALL_REVIEWS_REQUEST";
export const ADMIN_ALL_REVIEWS_SUCCESS = "ADMIN_ALL_REVIEWS_SUCCESS";
export const ADMIN_ALL_REVIEWS_FAILURE = "ADMIN_ALL_REVIEWS_FAILURE";

// clear error
export const CLEAR_ERROR = "CLEAR_ERROR";
