// All rooms by admin
export const ADMIN_ALL_ROOMS_REQUEST = "ADMIN_ALL_ROOMS_REQUEST";
export const ADMIN_ALL_ROOMS_SUCCESS = "ADMIN_ALL_ROOMS_SUCCESS";
export const ADMIN_ALL_ROOMS_FAILURE = "ADMIN_ALL_ROOMS_FAILURE";

// All rooms by admin
export const ADMIN_NEW_ROOM_REQUEST = "ADMIN_NEW_ROOM_REQUEST";
export const ADMIN_NEW_ROOM_SUCCESS = "ADMIN_NEW_ROOM_SUCCESS";
export const ADMIN_NEW_ROOM_FAILURE = "ADMIN_NEW_ROOM_FAILURE";
export const ADMIN_NEW_ROOM_RESET = "ADMIN_NEW_ROOM_RESET";

// clear error
export const CLEAR_ERROR = "CLEAR_ERROR";
