// check booking
export const CHECK_BOOKING_REQUEST = "CHECK_BOOKING_REQUEST";
export const CHECK_BOOKING_SUCCESS = "CHECK_BOOKING_SUCCESS";
export const CHECK_BOOKING_FAILURE = "CHECK_BOOKING_FAILURE";
export const CHECK_BOOKING_RESET = "CHECK_BOOKING_RESET";

// booked dates
export const BOOKED_DATES_SUCCESS = "BOOKED_DATES_SUCCESS";
export const BOOKED_DATES_FAILURE = "BOOKED_DATES_FAILURE";

// my bookings
export const MY_BOOKINGS_SUCCESS = "MY_BOOKINGS_SUCCESS";
export const MY_BOOKINGS_FAILURE = "MY_BOOKINGS_FAIL";

// bookings details
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAILURE = "BOOKING_DETAILS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
